### PR TITLE
new chunky wire format-less CPU, more tps

### PR DESCRIPTION
**Pull request by eostermueller**
Martin,

I made a performance enhancement -- now using a chunkier wire format instead of the chatty one in Release 31.  See results below for the improvements.  Most of the changes are in NetworkDataSenderThread and NetworkDataReceiverThread and I've added junits that test/demonstrate the new process.

Would you apply the change to InTrace base?
Thanks,
--Erik

Some notes:
* compression is no longer an option...always on.
* The graphs below detail the improvements in a steady state test with two threads of traffic, zero think time.  They show that CPU consumption is lower and throughput is higher.
* The following web application was used for the system under test:  https://github.com/eostermueller/headlessInTraceClient/tree/master/example.webapp
* Just a single method was traced:  example.webapp.servlet.HelloExecuteQuery
* tests were run without the option to capture the stack trace, which consumes a bit more cpu to capture those stack traces.

image

image

### CODE REVIEW

**Comment by eostermueller** [comment]
I forgot to mention this:

This breaks compatibility with previous versions.  

Specifically,

- New UI will not capture events from R31 or prior agent.  

- R31 or prior UI will not capture events from new agent.

**Comment by mchr3k** [comment]
Sorry for the delay, can you resolve the conflicts and then I'll accept the pull request? Thanks!

**Comment by eostermueller** [comment]
I'm sure it was my fault, but I couldn't find a way to update this pull request...never could tell which branch the changes resided on, so couldn't merge into that branch.

So I created a new branch in my downstream named 19and36.  This is the combined changes of both original pull requests.

https://github.com/eostermueller/org.intrace/tree/19and36

Perhaps I should just create a new pull request for branch 19and36?

--Erik

**Comment by eostermueller** [comment]
Martin, the combined changes for issue 19 and issue 36 are now sitting on master of https://github.com/eostermueller/org.intrace.git.

Let me know if you need anything else.

--Erik

**Pull request merged**
